---
# RedHat Specific Configs.
# roles/mysql/vars/RedHat.yml
mysql_socket: /var/lib/mysql/mysql.sock
mysql_cnfpath: /etc/my.cnf.d/my.cnf
mysql_service: mariadb
mysql_bind: 0.0.0.0
mysql_pkg: mariadb-server
