rechte:
	chmod 700 /vagrant/insecure_private*

ssh-setup: rechte
	ssh -i /vagrant/insecure_private_key 192.168.60.2 hostname
	ssh -i /vagrant/insecure_private_key 192.168.60.11 hostname
	ssh -i /vagrant/insecure_private_key 192.168.60.12 hostname
	ssh -i /vagrant/insecure_private_key 192.168.60.13 hostname
	ssh -i /vagrant/insecure_private_key 192.168.60.21 hostname
	ssh -i /vagrant/insecure_private_key 192.168.60.22 hostname
