---
- hosts: www
  remote_user: vagrant
  become: yes
  pre_tasks:
  - debug: 
      msg: 'I":" Beginning to configure web server..'

  roles:
     - nginx

  post_tasks:
  - debug:
      msg: 'I":" Done configuring nginx web server...'
