---
# tasks file for ssh_key
- name: ssh_key dem User Vagrant erstellen
  user:
    name: vagrant
    generate_ssh_key: yes
    ssh_key_passphrase: geheim
    ssh_key_type: rsa
    ssh_key_file: .ssh/id_rsa
    ssh_key_bits: 2048

- name: Publickey registrieren
  command: cat /home/vagrant/.ssh/id_rsa.pub
  register: pubkey
