---
 - name: add official nginx repository
   apt_repository:
     repo: 'ppa:nginx/stable'
     state: absent

 - name: install nginx web server and ensure its at the latest version
   apt: name=nginx state=latest force=yes
   tags:
    - install 
