---
- name: del official nginx repository
  apt_repository:
    repo: 'deb http://nginx.org/packages/ubuntu/ lucid nginx'
    state: absent

- name: add official nginx ppa/nginx
  apt_repository: repo='ppa:nginx/stable'

- name: install nginx web server and ensure its at the latest version
  apt: name=nginx state=latest force=yes
