---
- hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: Init AIS lxc containers
    expect:
      command: /home/vagrant/ais/hands-on-ansible/00-home-base/ais-lxc-setup.sh
      responses:
        (?i)password: "ubuntu"
      creates: /var/lib/lxc/ais-bashy
