---
  # filename: roles/wordpress/tasks/configure.yml
  - name: change permissions for wordpress site
    # Sets permissions for all WordPress files recursively.
    file:
      path: "{{ wp_docroot }}/{{ wp_sitedir }}"
      state: directory
      owner: "{{ wp_user }}"
      group: "{{ wp_group }}"
      recurse: true

  - name: get unique salt for wordpress
    # runs a command locally and registers the results in the
    # wp_salt variable. This is to provide WordPress with secret keys for
    # additional security. This variable will be used inside a template this time.
    local_action: command curl https://api.wordpress.org/secret-key/1.1/salt
    register: wp_salt

  - name: copy wordpress template
    # generate a Jinja2 template and copy it over to the target
    # host as the wp-config.php file.
    template:
      src: wp-config.php.j2
      dest: "{{ wp_docroot }}/{{ wp_sitedir }}/wp-config.php"
      mode: 0644
      